version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: MRKIOpostgres
      POSTGRES_PASSWORD: MRKIOpostgres
      POSTGRES_DB: MRKIODB
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    image: hohokio12/mr.kio:backend-latest
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_USER: MRKIOpostgres
      DB_PASSWORD: MRKIOpostgres
      DB_NAME: MRKIODB
      DB_PORT: "5432"
      JWT_SECRET: mysupersecretkey
      JWT_ISSUER: myapp.com
      JWT_AUDIENCE: myapp_users
      TZ: Asia/Taipei
      #CORS_ALLOW_ORIGIN: http://13.210.118.229 #前端
      COOKIE_DOMAIN: yourdomain.com

  frontend:
    image: hohokio12/mr.kio:frontend-latest
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      #- "3000:80"
      - "80:80"
    depends_on:
      - backend
      
volumes:
  postgres-data: 
  