name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull the latest images
      run: |
        # docker compose -f docker-compose.prod.yml pull
        docker compose pull

    - name: Stop and remove any existing containers
      run: |
        # docker compose -f docker-compose.prod.yml down
        docker compose down

    - name: Start the new containers
      run: |
        # docker compose -f docker-compose.prod.yml up -d
        docker compose up -d
